default_locale: pt_BR

some_setting:
  development: some setting development
  test: some setting test
  production: some setting production

upload_folder:
  development: /tmp
  test: /tmp
  production: /tmp
